# Generated by Django 4.0.2 on 2023-02-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_authority_alter_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='authority',
            new_name='zarinpal_authority',
        ),
    ]
