# Generated by Django 4.0.2 on 2023-03-13 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_zarinpal_data_order_zarinpal_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unique_code',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
